### ISSUE TITLE
Object scale issue in rendering

### ISSUE THREAD

**Issue by xianyongqin** [devlearning-gt/3DShapeGen#4]
Hi,

Thanks a lot for releasing the amazing codes. Everything works well except for this small rendering issue. 

We would like to make use of your rendering codes. However, I cannot get exactly the same images when I run wrapper.py with the default data_generation_parameters.json (my blender version is 2.79). The scale of the object is smaller than the provided rendered images. Here is an example. The first image is what I obtained by running wrapper.py and the second image is provided in your repo (ShapeNet55_3DOF-VC_LRBg).  In addition, current codes do not seem to support blending the background. Can you also released the background part? Thank you very much!

![0000](https://user-images.githubusercontent.com/52003678/120510075-5d887980-c3c9-11eb-9b09-f3a32115c18f.png)
![0014](https://user-images.githubusercontent.com/52003678/120510212-7d1fa200-c3c9-11eb-8c3a-e98ebb581a9b.png)

**Comment by sstojanov** [comment]
Thank you for reaching out with questions!

Some quick follow up questions:
- What ShapeNet version are you using? This can possibly affect how things work by default.
- What exactly is the (synset, object) pair in this example? The overall scale of the object in the scene can be made bigger or smaller depending on what's preferred. I can help you with this if you can tell me in more detail what you're trying to achieve.

Regarding the scripts to overlay the images on backgrounds, I can upload those shortly.

**Comment by xianyongqin** [comment]
-I am using ShapeNetv2
-synset: 04256520, object: e9d6a366a92a61d979c851829c339535
-I would like to produce the same rendered images with yours for a a fair comparison. I have to run the rendering myself to obtain more information. 

Can you double check if the data_generation_parameters.json you released  is exactly the same with the one you used to generate ShapeNet55_3DOF-VC_LRBg? 

Thank you very much!

**Comment by sstojanov** [comment]
Hi again,

The issue was that the` data_generation_parameters.json` uses a focal length of 35mm for rendering whereas the data we released uses 50mm. Thank you for pointing this out, we will make a commit and fix it.

<img width="255" alt="image" src="https://user-images.githubusercontent.com/13421307/121607240-ae2d5180-ca1d-11eb-9b85-661cbd8bb6b5.png">
Reference image from data release

<img width="257" alt="image" src="https://user-images.githubusercontent.com/13421307/121607271-bab1aa00-ca1d-11eb-95eb-c95a28be9dce.png">
Image rendered with "focal_length_mm"=50

----------------------------------------------------------------------------------------------

Regarding the background overlay code, please see the [following gist](https://gist.github.com/sstojanov/07aee9691c12a32d69b8a1a958ece599) which has code that will overlay the objects onto images from list of random backgrounds, with information on how to do it for SUN scenes.

Please be aware that this is parallelized code for faster run time and will change the images in place. 

Please feel free to re-open the issue if you have any further questions on this!
