### ISSUE TITLE
Depth map with cycles engine

### ISSUE THREAD

**Issue by hansongfang** [devlearning-gt/3DShapeGen#7]
Thank you for sharing the code! I have an issue with the depth map generation. It seems that the depth map rendered with cycles engine in blender 2.79 is not the z-value, which is the orthogonal distance. https://blender.stackexchange.com/questions/87504/blender-cycles-z-coordinate-vs-camera-centered-z-coordinate-orthogonal-distan

Will this depth map behavior affects the GenRe results? I think that the depth map used by GenRe rendered by Mitsuba is keeping the z-value.

**Comment by sstojanov** [comment]
Hi, thank you for your interest!

Just to clarify: Are you having any issues with our code base, or are you looking to get some clarifications?

In developing our code base we tested multiple cases where we successfully matched GenRe's Mitsuba data one-to-one. To our knowledge, in the GenRe implementation there is specifically a back-projection step that makes use of the per-pixel depth values treating them as rays from the camera origin ([this function](https://github.com/xiumingzhang/GenRe-ShapeHD/blob/ee42add2707de509b5914ab444ae91b832f75981/util/util_camera.py#L116)), which are denoted as `zs` in the diagram in the link you shared rather than the `zc`. 

In testing our code base we also used GenRe's backprojection code to take the Blender depth maps, backproject them and overlay them on top of the mesh to make sure that they match. Below is an example of an image, corresponding ground truth depth and normals, and a mesh derived from the backprojected depth shown from multiple views:

![image](https://user-images.githubusercontent.com/13421307/123983882-36a27080-d992-11eb-847a-cf4b2c96c9f8.png)

Please don't hesitate to ask if you have further questions!

**Comment by hansongfang** [comment]
Thank you so much for correcting me! I previously do not realize that GenRe's back-projection step is using the sight ray's length. Your answer solves my question. :smile:
